# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('date', models.DateField()),
                ('enddate', models.DateField()),
                ('exception', models.DateField()),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('date', models.DateField()),
                ('enddate', models.DateField()),
                ('exception', models.DateField()),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Clases',
        ),
    ]
