# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_auto_20171220_1635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workshops',
            new_name='Cycle',
        ),
        migrations.RenameModel(
            old_name='Cycles',
            new_name='Workshop',
        ),
    ]
