# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0003_auto_20171220_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='invitation',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
