# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0004_workshop_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('class_type', models.CharField(choices=[('CY', 'Cycle'), ('WO', 'Workshop'), ('FE', 'Festival')], max_length=2)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('date', models.DateField()),
                ('enddate', models.DateField()),
                ('exception', models.DateField()),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Cycle',
        ),
        migrations.DeleteModel(
            name='Workshop',
        ),
    ]
