# Generated by Django 2.0.9 on 2019-02-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('EI', 'Einkommen'), ('KO', 'Kosten'), ('AU', 'Ausgaben'), ('IN', 'Inversion'), ('LO', 'Lohn'), ('SP', 'Spargeld')], max_length=10)),
                ('amount', models.CharField(max_length=9)),
                ('pay_till', models.DateField(blank=True, null=True)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('methode', models.CharField(blank=True, choices=[('BT', 'Bank'), ('TW', 'Twint'), ('PP', 'PayPal'), ('CS', 'Cash'), ('CR', 'Credit Card'), ('UN', 'Unclasified')], default='UN', max_length=15, null=True)),
                ('status', models.CharField(blank=True, choices=[('IN', 'Informed'), ('CA', 'Canceled'), ('PA', 'Payed'), ('PE', 'Pending'), ('SW', 'Switched')], max_length=15, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('degistered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
