# Generated by Django 2.0.9 on 2019-02-08 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('balance', models.CharField(choices=[('AS', 'Assets'), ('EQ', 'Equity'), ('LI', 'Liabilities')], max_length=11)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='PE', max_length=10)),
                ('pay_till', models.DateField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=9)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('methode', models.CharField(blank=True, choices=[('BT', 'Bank'), ('TW', 'Twint'), ('PP', 'PayPal'), ('CS', 'Cash'), ('CR', 'Credit Card'), ('UN', 'Unclasified')], default='UN', max_length=15, null=True)),
                ('degistered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Accounting',
        ),
    ]
