# Generated by Django 2.0.9 on 2019-04-30 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='invoice',
        #     name='booking',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Booking'),
        # ),
        migrations.AddField(
            model_name='invoice',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Partner'),
        ),
    ]
