# Generated by Django 2.2.4 on 2019-08-26 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.Book",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounting.Partner",
            ),
        ),
    ]
