# Generated by Django 2.2.2 on 2019-06-24 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20190525_1550'),
        ('accounting', '0002_auto_20190430_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='booking',
        ),
        migrations.AddField(
            model_name='invoice',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Book'),
        ),
    ]
