# Generated by Django 2.2.9 on 2020-01-30 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_auto_20191009_1724"),
        ("accounting", "0003_auto_20191118_0943"),
    ]

    operations = [
        migrations.RemoveField(model_name="transaction", name="account",),
        migrations.RemoveField(model_name="transaction", name="invoice",),
        migrations.RemoveField(model_name="transaction", name="payment",),
        migrations.RemoveField(model_name="invoice", name="amount",),
        migrations.RemoveField(model_name="partner", name="account",),
        migrations.RemoveField(model_name="partner", name="description_pay",),
        migrations.AddField(
            model_name="invoice",
            name="balance",
            field=models.CharField(choices=[("DB", "DEBIT"), ("CR", "CREDIT")], default="DB", max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice", name="id_code", field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="methode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BT", "Bank"),
                    ("TW", "Twint"),
                    ("PP", "PayPal"),
                    ("CS", "Cash"),
                    ("CR", "Credit Card"),
                    ("UN", "Unclasified"),
                ],
                default="UN",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice", name="notes", field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(model_name="invoice", name="pay_date", field=models.DateField(blank=True, null=True),),
        migrations.AddField(
            model_name="invoice", name="payed", field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice", name="to_pay", field=models.PositiveIntegerField(default=0), preserve_default=False,
        ),
        migrations.AddField(
            model_name="partner",
            name="address",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="address.Address"
            ),
        ),
        migrations.AddField(
            model_name="partner", name="bank_name", field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="partner", name="iban", field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="partner", name="notes", field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="partner", name="swift", field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(name="Account",),
        migrations.DeleteModel(name="Payment",),
        migrations.DeleteModel(name="Transaction",),
    ]
