# Generated by Django 2.2.9 on 2020-02-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_auto_20200202_1511"),
    ]

    operations = [
        migrations.RenameField(model_name="invoice", old_name="id_code", new_name="referral_code",),
    ]
