# Generated by Django 2.2.11 on 2020-03-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0007_auto_20200202_1514"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="paid",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="invoice", name="to_pay", field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
