# Generated by Django 2.2.13 on 2020-09-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20200325_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='methode',
            field=models.CharField(blank=True, choices=[('BT', 'Bank'), ('TW', 'Twint'), ('PP', 'PayPal'), ('CS', 'Cash'), ('CR', 'Credit Card'), ('UN', 'Unclasified'), ('RC', 'Recovery Card')], default='UN', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='prefered_pay',
            field=models.CharField(blank=True, choices=[('BT', 'Bank'), ('TW', 'Twint'), ('PP', 'PayPal'), ('CS', 'Cash'), ('CR', 'Credit Card'), ('UN', 'Unclasified'), ('RC', 'Recovery Card')], max_length=15, null=True),
        ),
    ]
