# Generated by Django 2.2.17 on 2020-11-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_auto_20200902_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('PY', 'Paid'), ('CA', 'Canceled'), ('ST', 'Storno'), ('FR', 'First Reminder'), ('SR', 'Second Reminder'), ('TR', 'Third Reminder')], default='PE', max_length=10),
        ),
    ]
