# Generated by Django 2.2.17 on 2020-11-27 18:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_auto_20201127_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reminder_dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), null=True, size=3),
        ),
    ]
