# Generated by Django 2.2.17 on 2020-12-22 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_auto_20201130_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_credit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credited_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('PY', 'Paid')], default='PE', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Creditnotedate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('creditnote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Creditnote')),
            ],
        ),
    ]
