# Generated by Django 2.2.4 on 2019-08-26 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to="address.Address",),
        ),
        migrations.AlterField(model_name="user", name="phone", field=models.CharField(blank=True, max_length=50),),
    ]
