# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-29 14:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AboutGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AboutMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(choices=[('fas fa-redo', 'Masterclass'), ('fas fa-rocket', 'Festival'), ('fas fa-cogs', 'Cycle'), ('fas fa-cog', 'Workshop'), ('fas fa-star', 'Camp'), ('fas fa-star', 'Retreat')], default=1, max_length=13)),
                ('level', models.CharField(choices=[('A', 'Advanced'), ('B', 'Intermediate'), ('C', 'Introdution'), ('Z', 'Multilevel')], default=1, max_length=1)),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=300)),
                ('prerequisites', models.TextField(blank=True, max_length=300, null=True)),
                ('location', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=20)),
                ('ocurrance', models.CharField(blank=True, choices=[('Wed', "Wednesday's"), ('Thu', "Thursday's"), ('Sun', "Sunday's"), ('WedSun.', "Wed. & Sunday's"), ('Year', 'Yearly'), ('One', 'One Time')], max_length=8, null=True)),
                ('datestart', models.DateTimeField(blank=True, null=True)),
                ('dateend', models.DateTimeField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('publication', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=30, null=True)),
                ('sec_text', models.TextField(blank=True, max_length=30, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ImageField(upload_to='portfolio/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=350)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
    ]
