# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-24 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=30)),
                ('member_position', models.CharField(max_length=30)),
                ('member_content', models.CharField(max_length=300)),
            ],
        ),
    ]
