# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-23 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='about/general/')),
            ],
        ),
        migrations.RenameModel(
            old_name='AboutGeneral',
            new_name='About',
        ),
        migrations.DeleteModel(
            name='AboutGeneralImage',
        ),
        migrations.AddField(
            model_name='aboutimage',
            name='general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.About'),
        ),
    ]
