# Generated by Django 2.2.2 on 2019-06-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdate',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutdate',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
