# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-25 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180224_2247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutContent',
            new_name='AboutMember',
        ),
    ]
