# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-23 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_portfolio_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='order',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
