# Generated by Django 2.2.4 on 2019-08-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20190826_2037"),
    ]

    operations = [
        migrations.CreateModel(
            name="Whatsapp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.TextField(max_length=350)),
            ],
        ),
    ]
