# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-30 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutimage',
            name='about',
        ),
        migrations.AddField(
            model_name='aboutimage',
            name='general',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='generalimages', to='home.AboutGeneral'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutimage',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memberimages', to='home.AboutMember'),
            preserve_default=False,
        ),
    ]
