# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-25 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180225_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_description', models.CharField(max_length=300)),
                ('general_dates', models.CharField(max_length=20)),
            ],
        ),
    ]
