# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-30 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180330_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutGeneralImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.AboutGeneral')),
            ],
        ),
        migrations.CreateModel(
            name='AboutMemberImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberimages', to='home.AboutMember')),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutimage',
            name='general',
        ),
        migrations.RemoveField(
            model_name='aboutimage',
            name='member',
        ),
        migrations.DeleteModel(
            name='AboutImage',
        ),
    ]
