# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-01 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180501_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('abo', models.CharField(blank=True, choices=[('SA', 'Season Abo'), ('CY', 'Cycle Abo'), ('SI', 'Single Ticket')], max_length=8, null=True)),
                ('option', models.CharField(blank=True, max_length=5, null=True)),
                ('comment', models.TextField(blank=True, max_length=350, null=True)),
                ('payment', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('note', models.TextField(blank=True, max_length=1000, null=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='cat',
            field=models.CharField(choices=[('fas fa-redo', 'Masterclass'), ('fas fa-rocket', 'Festival'), ('fas fa-cogs', 'Cycle'), ('fas fa-cog', 'Workshop'), ('fas fa-star', 'Camp'), ('fas fa-seedling', 'Retreat')], default=1, max_length=13),
        ),
        migrations.AddField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Event'),
        ),
    ]
