# Generated by Django 2.2.4 on 2019-10-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_whatsapp"),
    ]

    operations = [
        migrations.DeleteModel(name="Whatsapp",),
        migrations.RemoveField(model_name="aboutimage", name="general",),
        migrations.DeleteModel(name="About",),
    ]
