# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-03 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180330_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmemberimage',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.AboutMember'),
        ),
    ]
