# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-01 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180501_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cat',
            field=models.CharField(choices=[('fas fa-redo', 'Masterclass'), ('fas fa-rocket', 'Festival'), ('fas fa-cogs', 'Cycle'), ('fas fa-cog', 'Workshop'), ('fas fa-star', 'Camp'), ('fas fa-seedling', 'Retreat')], default=1, max_length=15),
        ),
    ]
