# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-25 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180225_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdate',
            name='date_description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
