# Generated by Django 2.2.10 on 2020-02-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200214_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslist',
            name='image',
            field=models.ImageField(upload_to='news/'),
        ),
    ]
