# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-04 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180403_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutgeneralimage',
            name='general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.AboutGeneral'),
        ),
        migrations.AlterField(
            model_name='aboutmemberimage',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.AboutMember'),
        ),
    ]
