# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-07 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_booking_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Event'),
            preserve_default=False,
        ),
    ]
