# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-07 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_booking_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pay_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('IN', 'Informed'), ('CA', 'Canceled'), ('PA', 'Payed'), ('PE', 'Pending'), ('SW', 'Switched')], max_length=15, null=True),
        ),
    ]
