# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-25 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180225_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_event', models.CharField(choices=[('Repeat', '<i class="fas fa-redo">'), ('Special', '<i class="fas fa-star"></i>'), ('Cycle', '<i class="fas fa-cogs"></i>'), ('Workshop', '<i class="fas fa-cog"></i>')], max_length=7)),
                ('title_event', models.CharField(max_length=60)),
                ('description_event', models.CharField(max_length=300)),
                ('prerequisites_event', models.CharField(blank=True, max_length=300, null=True)),
                ('location_event', models.CharField(max_length=60)),
                ('city_event', models.CharField(max_length=20)),
                ('datestart_event', models.DateTimeField(blank=True, null=True)),
                ('dateend_event', models.DateTimeField(blank=True, null=True)),
                ('ocurrance_event', models.CharField(choices=[('Wed', 'Weekly Wednesday'), ('Tue', 'Weekly Thursday'), ('Sun', 'Weekly Sunday'), ('Once', 'One Time Event'), ('Year', 'Yearly Event')], max_length=7)),
                ('duration_event', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
