# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-04 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180404_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cat',
            field=models.CharField(choices=[('fas fa-redo', 'Masterclass'), ('fas fa-rocket', 'Festival'), ('fas fa-cogs', 'Cycle'), ('fas fa-cog', 'Workshop'), ('fas fa-star', 'Training Camp'), ('fas fa-star', 'Retreat')], default=1, max_length=13),
        ),
        migrations.AlterField(
            model_name='event',
            name='ocurrance',
            field=models.CharField(blank=True, choices=[('Mon', "Monday's"), ('Wed', "Wednesday's"), ('Thu', "Thursday's"), ('Sun', "Sunday's"), ('WedSun.', "Wed. & Sunday's"), ('Year', 'Yearly'), ('One', 'One Time')], max_length=8, null=True),
        ),
    ]
