# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-26 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type_event',
            field=models.CharField(choices=[('Masterclass', '<i class="fas fa-redo">'), ('Special', '<i class="fas fa-star"></i>'), ('Cycle', '<i class="fas fa-cogs"></i>'), ('Workshop', '<i class="fas fa-cog"></i>')], max_length=11),
        ),
    ]
