# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-16 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_newslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reduction',
            field=models.CharField(blank=True, choices=[('ST', 'Student'), ('NM', 'Normal')], max_length=12, null=True),
        ),
    ]
