# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-26 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20180226_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type_event',
            field=models.CharField(choices=[('Masterclass', 'fas fa-rocket'), ('Special', 'fas fa-star'), ('Cycle', 'fas fa-cogs'), ('Workshop', 'fas fa-cog')], max_length=11),
        ),
    ]
