# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-24 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20180517_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
