# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-26 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20180226_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type_event',
            field=models.CharField(choices=[('fas fa-redo', 'Masterclass'), ('fas fa-star', 'Special'), ('fas fa-cogs', 'Cycle'), ('fas fa-cog', 'Workshop')], max_length=11),
        ),
    ]
