# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-24 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_event_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration',
            field=models.BooleanField(default=True),
        ),
    ]
