# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-30 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_event_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='option',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
