# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-28 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20180227_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='type_event',
            new_name='cat',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='city_event',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='dateend_event',
            new_name='dateend',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='datestart_event',
            new_name='datestart',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description_event',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='duration_event',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='location_event',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='prerequisites_event',
            new_name='prerequisites',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title_event',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ocurrance_event',
        ),
        migrations.AddField(
            model_name='event',
            name='ocurrance',
            field=models.CharField(blank=True, choices=[('Wed', 'Every Wed'), ('Tue', 'Every Tue'), ('Sun', 'Every Sun'), ('Year', 'Yearly'), ('Once', 'Special One Time')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
