# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-21 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20180721_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='day',
            field=models.CharField(blank=True, choices=[('Wed', "Wednesday's"), ('Sun', "Sunday's"), ('WedSun.', "Wed. & Sunday's")], max_length=8, null=True),
        ),
    ]
