# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-28 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20180228_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.AlterField(
            model_name='event',
            name='ocurrance',
            field=models.CharField(blank=True, choices=[('Wed', 'Every Wed'), ('Tue', 'Every Tue'), ('Sun', 'Every Sun'), ('Wed, Sun', 'Every Wed and Sun'), ('Year', 'Yearly'), ('Once', 'Special One Time')], max_length=7, null=True),
        ),
    ]
