# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('EI', 'Einkommen'), ('KO', 'Kosten'), ('AU', 'Ausgaben'), ('IN', 'Inversion'), ('LO', 'Lohn'), ('SP', 'Spargeld')], max_length=10)),
                ('amount', models.CharField(max_length=9)),
                ('pay_till', models.DateField(blank=True, null=True)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('methode', models.CharField(blank=True, choices=[('BT', 'Bank'), ('TW', 'Twint'), ('PP', 'PayPal'), ('CS', 'Cash'), ('CR', 'Credit Card'), ('UN', 'Unclasified')], default='UN', max_length=15, null=True)),
                ('status', models.CharField(blank=True, choices=[('IN', 'Informed'), ('CA', 'Canceled'), ('PA', 'Payed'), ('PE', 'Pending'), ('SW', 'Switched')], max_length=15, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('degistered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='payment',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.CharField(choices=[('EI', 'Einkommen')], default='EI', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='methode',
            field=models.CharField(blank=True, choices=[('BT', 'Bank'), ('TW', 'Twint'), ('PP', 'PayPal'), ('CS', 'Cash'), ('CR', 'Credit Card'), ('UN', 'Unclasified')], default='UN', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ocurrance',
            field=models.CharField(blank=True, choices=[('Mon', "Monday's"), ('Tue', "Tuesday's"), ('Wed', "Wednesday's"), ('Thu', "Thursday's"), ('Fri', "Friday's"), ('Sun', "Sunday's"), ('WedSun.', "Wed. & Sunday's"), ('TueSun.', "Tue. & Sunday's"), ('Year', 'Yearly'), ('One', 'One Time')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='accounting',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Event'),
        ),
    ]
