# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-01 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20180830_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='category',
            field=models.CharField(choices=[('EI', 'Einkommen'), ('KO', 'Kosten'), ('AU', 'Ausgaben'), ('IN', 'Inversion'), ('LO', 'Lohn'), ('SP', 'Spargeld')], default='EI', max_length=10),
        ),
    ]
