# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-28 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20180228_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ocurrance',
            field=models.CharField(blank=True, choices=[('Wed.', 'Every Wed'), ('Tue.', 'Every Tue'), ('Sun.', 'Every Sun'), ('Wed. and Sun.', 'Every Wed and Sun'), ('Yearly', 'Yearly'), ('One Time', 'Special One Time')], max_length=7, null=True),
        ),
    ]
