# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20180901_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.CharField(blank=True, choices=[('Wed', "Wednesday's"), ('Tue', "Tuesday's"), ('Sun', "Sunday's"), ('WedSun.', "Wed. & Sunday's"), ('TueWed.', "Tue. & Wednesday's"), ('TueSun.', "Tue. & Sunday's")], max_length=8, null=True),
        ),
    ]
