# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-28 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20180228_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ocurrance',
            field=models.CharField(blank=True, choices=[('Wed', "Wednesday's"), ('Tue', "Tuersday's"), ('Sun', "Sunday's"), ('WedSun.', "Wed. and Sunday's"), ('Yearly', 'Yearly'), ('One Time', 'One Time')], max_length=8, null=True),
        ),
    ]
