# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-28 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20180228_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=350)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='ocurrance',
            field=models.CharField(blank=True, choices=[('Wed', "Wednesday's"), ('Tue', "Tuersday's"), ('Sun', "Sunday's"), ('WedSun.', "Wed. & Sunday's"), ('Yearly', 'Yearly'), ('One Time', 'One Time')], max_length=8, null=True),
        ),
    ]
