# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20181002_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='abo',
            field=models.CharField(blank=True, choices=[('SA', 'Single Season Abo'), ('SD', 'Double Season Abo'), ('CY', 'Single Cycle Abo'), ('CD', 'Double Cycle Abo'), ('SI', 'Single Day Ticket')], max_length=8, null=True),
        ),
    ]
