# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-28 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20180228_1142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonal',
            new_name='Testimonial',
        ),
    ]
