# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-01 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20180228_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='level',
            field=models.CharField(choices=[('A', 'Avd.'), ('B', 'Intm.'), ('C', 'Intro.'), ('Z', 'Multi.')], default='Multi.', max_length=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='cat',
            field=models.CharField(choices=[('fas fa-redo', 'Masterclass'), ('fas fa-rocket', 'Festival'), ('fas fa-cogs', 'Cycle'), ('fas fa-cog', 'Workshop'), ('fas fa-star', 'Camp')], default='Cycle', max_length=13),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='ocurrance',
            field=models.CharField(blank=True, choices=[('Wed', "Wednesday's"), ('Thu', "Thursday's"), ('Sun', "Sunday's"), ('WedSun.', "Wed. & Sunday's"), ('Year', 'Yearly'), ('One', 'One Time')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='prerequisites',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(max_length=350),
        ),
    ]
