# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-01 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20180301_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cat',
            field=models.CharField(choices=[('fas fa-redo', 'Masterclass'), ('fas fa-rocket', 'Festival'), ('fas fa-cogs', 'Cycle'), ('fas fa-cog', 'Workshop'), ('fas fa-star', 'Camp')], default=1, max_length=13),
        ),
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.CharField(choices=[('A', 'Advanced'), ('B', 'Intermediate'), ('C', 'Introdution'), ('Z', 'Multilevel')], default=1, max_length=1),
        ),
    ]
