# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-01 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_event_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
