# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-01 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cat',
            field=models.CharField(choices=[('fas fa-redo', 'Masterclass'), ('fas fa-rocket', 'Festival'), ('fas fa-cogs', 'Cycle'), ('fas fa-cog', 'Workshop'), ('fas fa-star', 'Camp'), ('fas fa-star', 'Retreat')], default=1, max_length=13),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
