# Generated by Django 2.0.9 on 2019-05-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20190525_1550'),
        ('home', '0032_auto_20190508_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='event',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
