# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-02 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20180302_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileitem',
            name='event',
        ),
    ]
