# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-02 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_fileitem_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=30, null=True)),
                ('sec_text', models.TextField(blank=True, max_length=30, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.FileItem')),
            ],
        ),
        migrations.RenameField(
            model_name='aboutdate',
            old_name='date_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='aboutdate',
            old_name='date_end',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='aboutdate',
            old_name='date_start',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='aboutmember',
            old_name='member_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='aboutmember',
            old_name='member_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='aboutmember',
            old_name='member_position',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='aboutgeneral',
            name='general_description',
        ),
        migrations.AddField(
            model_name='aboutgeneral',
            name='description',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutgeneral',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.FileItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutmember',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.FileItem'),
            preserve_default=False,
        ),
    ]
