# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-27 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20180302_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='aboutgeneral',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutmember',
            name='image',
        ),
        migrations.RemoveField(
            model_name='media',
            name='image',
        ),
        migrations.DeleteModel(
            name='FileItem',
        ),
    ]
