# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-27 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_portafolio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portafolio',
            new_name='Portfolio',
        ),
    ]
