# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-27 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20180327_1516'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sec_text',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='text',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='upload',
            field=models.ImageField(upload_to='portfolio/'),
        ),
    ]
