# Generated by Django 2.2.2 on 2019-06-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='staff',
            field=models.ManyToManyField(blank=True, to='users.Staff'),
        ),
    ]
