# Generated by Django 2.0.9 on 2019-04-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeoption',
            name='doors_interval',
        ),
        migrations.AddField(
            model_name='timeoption',
            name='class_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeoption',
            name='class_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeoption',
            name='open_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeoption',
            name='open_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
