# Generated by Django 2.0.9 on 2019-02-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Policies',
            new_name='Policy',
        ),
    ]
