# Generated by Django 2.0.9 on 2019-02-08 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190205_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Location')),
            ],
        ),
        migrations.RenameField(
            model_name='timeoption',
            old_name='open_time',
            new_name='open_interval',
        ),
        migrations.RenameField(
            model_name='timeoption',
            old_name='start_time',
            new_name='start_interval',
        ),
        migrations.RemoveField(
            model_name='event',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='event',
            name='timeoptions',
        ),
        migrations.RemoveField(
            model_name='timeoption',
            name='days',
        ),
        migrations.AddField(
            model_name='timeoption',
            name='days',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Day'),
        ),
        migrations.AddField(
            model_name='timelocation',
            name='timeoptions',
            field=models.ManyToManyField(to='project.TimeOption'),
        ),
        migrations.AddField(
            model_name='event',
            name='timelocation',
            field=models.ManyToManyField(to='project.TimeLocation'),
        ),
    ]
