# Generated by Django 2.0.9 on 2019-04-30 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20190430_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='priceoptions',
            new_name='price_options',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='timelocation',
            new_name='time_location',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='max_participants',
            new_name='max_participants_capacity',
        ),
        migrations.RenameField(
            model_name='timelocation',
            old_name='timeoptions',
            new_name='time_options',
        ),
        migrations.RenameField(
            model_name='timeoption',
            old_name='days',
            new_name='regular_days',
        ),
        migrations.RemoveField(
            model_name='event',
            name='eventend_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='eventstart_date',
        ),
        migrations.RemoveField(
            model_name='exception',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='exception',
            name='start_date',
        ),
        migrations.AddField(
            model_name='exception',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exception',
            name='time_location',
            field=models.ManyToManyField(to='project.TimeLocation'),
        ),
        migrations.AlterField(
            model_name='exception',
            name='category',
            field=models.CharField(choices=[('TI', 'Time'), ('LO', 'Location'), ('TL', 'TimeLocation')], max_length=15),
        ),
        migrations.AlterField(
            model_name='timeoption',
            name='class_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeoption',
            name='class_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeoption',
            name='open_end',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeoption',
            name='open_start',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
