# Generated by Django 2.0.9 on 2019-04-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190430_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_location',
            field=models.ManyToManyField(related_name='timelocatin', to='project.TimeLocation'),
        ),
    ]
