# Generated by Django 2.2.4 on 2019-10-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20191021_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='exceptions',
            field=models.ManyToManyField(to='project.Exception'),
        ),
    ]
