# Generated by Django 2.0.9 on 2019-04-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20190430_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='max_participants',
            new_name='maxparticipants',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='price_options',
            new_name='priceoptions',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='time_location',
            new_name='timelocation',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='max_participants_capacity',
            new_name='maxparticipantscapacity',
        ),
        migrations.RenameField(
            model_name='priceoption',
            old_name='price_CHF',
            new_name='pricechf',
        ),
        migrations.RenameField(
            model_name='priceoption',
            old_name='price_EURO',
            new_name='priceeuro',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='timelocation',
            old_name='time_options',
            new_name='timeoptions',
        ),
        migrations.RenameField(
            model_name='timeoption',
            old_name='class_end',
            new_name='classend',
        ),
        migrations.RenameField(
            model_name='timeoption',
            old_name='class_start',
            new_name='classstart',
        ),
        migrations.RenameField(
            model_name='timeoption',
            old_name='end_date',
            new_name='enddate',
        ),
        migrations.RenameField(
            model_name='timeoption',
            old_name='open_end',
            new_name='openend',
        ),
        migrations.RenameField(
            model_name='timeoption',
            old_name='open_start',
            new_name='openstart',
        ),
        migrations.RenameField(
            model_name='timeoption',
            old_name='start_date',
            new_name='startdate',
        ),
    ]
