# Generated by Django 2.2.4 on 2019-10-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_event_exceptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event", name="exceptions", field=models.ManyToManyField(blank=True, to="project.Exception"),
        ),
    ]
