# Generated by Django 2.0.9 on 2019-05-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20190430_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='timelocation',
        ),
        migrations.AddField(
            model_name='event',
            name='timelocations',
            field=models.ManyToManyField(to='project.TimeLocation'),
        ),
    ]
