# Generated by Django 2.0.9 on 2019-05-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_event_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeoption',
            options={'get_latest_by': 'enddate'},
        ),
    ]
