# Generated by Django 2.2.6 on 2019-11-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0009_event_cycle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="cycle",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, 0),
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                    (11, 11),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
