# Generated by Django 2.0.9 on 2019-05-04 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20190504_0830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['timelocations__timeoptions__startdate']},
        ),
    ]
