# Generated by Django 2.0.9 on 2019-05-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20190504_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='timeoption',
            options={},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='maxparticipants',
            new_name='max_participants',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='priceoptions',
            new_name='price_options',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='timelocations',
            new_name='time_locations',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='maxparticipantscapacity',
            new_name='max_capacity',
        ),
        migrations.RenameField(
            model_name='priceoption',
            old_name='pricechf',
            new_name='price_chf',
        ),
        migrations.RenameField(
            model_name='priceoption',
            old_name='priceeuro',
            new_name='price_euro',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='date_creation',
            new_name='creationdate',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='firstname',
            new_name='firs_tname',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='timelocation',
            old_name='timeoptions',
            new_name='time_options',
        ),
        migrations.RenameField(
            model_name='timeoption',
            old_name='classend',
            new_name='class_endtime',
        ),
        migrations.RenameField(
            model_name='timeoption',
            old_name='classstart',
            new_name='class_starttime',
        ),
        migrations.RenameField(
            model_name='timeoption',
            old_name='openend',
            new_name='open_starttime',
        ),
        migrations.RenameField(
            model_name='timeoption',
            old_name='openstart',
            new_name='openend_endtime',
        ),
        migrations.RemoveField(
            model_name='timeoption',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='timeoption',
            name='startdate',
        ),
        migrations.AddField(
            model_name='event',
            name='event_enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
