# Generated by Django 2.0.9 on 2019-05-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20190504_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='firs_tname',
            new_name='firs_name',
        ),
    ]
