# Generated by Django 2.2.9 on 2020-01-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0012_auto_20191116_1246"),
    ]

    operations = [
        migrations.AddField(
            model_name="priceoption",
            name="cycles",
            field=models.IntegerField(
                default=1, verbose_name="Numbero of Cycles"
            ),
            preserve_default=False,
        ),
    ]
