# Generated by Django 2.2.11 on 2020-03-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_priceoption_cycles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceoption',
            name='price_chf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='priceoption',
            name='price_euro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
