# Generated by Django 2.0.9 on 2019-05-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20190504_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeoption',
            old_name='openend_endtime',
            new_name='open_endtime',
        ),
    ]
