# Generated by Django 2.0.9 on 2019-05-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20190504_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='categorie',
            field=models.CharField(choices=[('fas fa-redo', 'Masterclass'), ('fas fa-rocket', 'Festival'), ('fas fa-cogs', 'Cycle'), ('fas fa-cog', 'Workshop'), ('fas fa-star', 'Camp'), ('fas fa-seeding', 'Retreat')], max_length=50),
        ),
    ]
