# Generated by Django 2.0.9 on 2019-05-06 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20190506_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='categorie',
            new_name='category',
        ),
    ]
