# Generated by Django 2.0.9 on 2019-05-25 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('project', '0017_auto_20190506_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='team',
        ),
        migrations.AddField(
            model_name='event',
            name='staff',
            field=models.ManyToManyField(to='users.Staff'),
        ),
        migrations.AddField(
            model_name='event',
            name='teacher',
            field=models.ManyToManyField(to='users.Teacher'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ManyToManyField(to='users.Staff'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
