# Generated by Django 2.2.12 on 2020-04-21 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0019_priceoption_ask_date"),
    ]

    operations = [
        migrations.RenameField(model_name="priceoption", old_name="ask_date", new_name="single_date",),
    ]
