# Generated by Django 2.2.12 on 2020-05-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0020_auto_20200421_1521"),
    ]

    operations = [
        migrations.AlterField(model_name="policy", name="description", field=models.TextField(max_length=5000),),
    ]
