# Generated by Django 2.2.13 on 2020-08-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20200824_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelocation',
            name='name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
