# Generated by Django 2.2.13 on 2020-08-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_timelocation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelocation',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
