# Generated by Django 2.2.13 on 2020-09-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_auto_20200831_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeoption',
            old_name='regular_days',
            new_name='regular_day',
        ),
    ]
