# Generated by Django 2.2.16 on 2020-09-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_auto_20200901_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoption',
            name='regular_day',
            field=models.CharField(blank=True, choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=10, null=True),
        ),
    ]
