# Generated by Django 2.2.16 on 2020-09-16 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_auto_20200907_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='todo',
            new_name='public_chat_link',
        ),
    ]
