# Generated by Django 2.2.16 on 2020-11-03 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_auto_20201103_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_enddate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_startdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
