# Generated by Django 2.2.17 on 2020-11-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_auto_20201103_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceoption',
            name='cycles',
            field=models.IntegerField(default=0, verbose_name='Number of Cycles'),
        ),
    ]
