# Generated by Django 2.2.17 on 2020-12-08 14:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_auto_20201127_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelocation',
            name='time_option',
            field=models.ForeignKey(default="3", on_delete=django.db.models.deletion.PROTECT, related_name='time_option', to='project.TimeOption'),
            preserve_default=False,
        ),
    ]
