# Generated by Django 2.2.17 on 2020-12-08 14:17

from __future__ import unicode_literals
from django.db import migrations, models


def make_many_authors(apps, schema_editor):
    """
        Adds the Author object in Book.author to the
        many-to-many relationship in Book.authors
    """
    TimeLocation = apps.get_model('project', 'TimeLocation')

    for tl in TimeLocation.objects.all():
        tl.time_option = tl.time_options.last()
        tl.save()


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_timelocation_time_option'),
    ]

    operations = [
        migrations.RunPython(make_many_authors),
    ]
