# Generated by Django 2.2.17 on 2020-12-08 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_auto_20201208_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.Location'),
        ),
    ]
