# Generated by Django 2.2.17 on 2020-12-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_auto_20201208_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creationdate',
            new_name='created_on',
        ),
    ]
