# Generated by Django 2.0.9 on 2019-04-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0031_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True, max_length=350, null=True)),
                ('status', models.CharField(blank=True, choices=[('PE', 'Pending'), ('WL', 'Waiting List'), ('IN', 'Informed'), ('PA', 'Participant'), ('CA', 'Canceled'), ('SW', 'Switched')], max_length=15, null=True)),
                ('note', models.TextField(blank=True, max_length=1000, null=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ManyToManyField(to='home.Address')),
            ],
        ),
    ]
