# Generated by Django 2.2.4 on 2019-08-26 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("booking", "0001_initial"), ("project", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="book",
            name="event",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="project.Event"),
        ),
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="project.PriceOption",),
        ),
        migrations.AddField(
            model_name="book",
            name="time",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="project.TimeOption",),
        ),
    ]
