# Generated by Django 2.2.6 on 2019-11-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("booking", "0004_auto_20191023_1528")]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PE", "Pending"),
                    ("WL", "Waiting List"),
                    ("IN", "Informed"),
                    ("PA", "Participant"),
                    ("CA", "Canceled"),
                    ("SW", "Switched"),
                ],
                default="PE",
                max_length=15,
                null=True,
            ),
        )
    ]
