# Generated by Django 2.2.6 on 2019-11-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("booking", "0005_auto_20191106_1234")]

    operations = [
        migrations.RenameField(
            model_name="book", old_name="time", new_name="times"
        )
    ]
