# Generated by Django 2.2.9 on 2019-12-26 17:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_auto_20191106_1241"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assistance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assistance_date",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DateField(), size=None
                    ),
                ),
                (
                    "assistance_check",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.BooleanField(), size=None
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.Book",
                    ),
                ),
            ],
        ),
    ]
