# Generated by Django 2.2.9 on 2020-01-10 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_auto_20200110_1120"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistance",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.Book",
                unique=True,
            ),
        ),
    ]
