# Generated by Django 2.2.9 on 2020-01-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_auto_20200110_1133"),
    ]

    operations = [
        migrations.RenameModel(old_name="Assistance", new_name="Attendance",),
        migrations.RenameField(
            model_name="attendance",
            old_name="assistance_check",
            new_name="attendance_check",
        ),
        migrations.RenameField(
            model_name="attendance",
            old_name="assistance_date",
            new_name="attendance_date",
        ),
    ]
