# Generated by Django 2.2.9 on 2020-02-07 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0011_auto_20200207_0937"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="book",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="booking.Book"
            ),
        ),
    ]
