# Generated by Django 2.2.11 on 2020-03-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0014_auto_20200322_1741"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="locked",
            field=models.BooleanField(default=False),
        ),
    ]
