# Generated by Django 2.2.11 on 2020-03-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0015_auto_20200325_1016"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="acrolama_profit",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="direct_revenue",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="fix_profit",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="teachers_profit",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="total_attendees",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
