# Generated by Django 2.2.11 on 2020-04-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_auto_20200330_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='related_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
