# Generated by Django 2.2.12 on 2020-04-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20200402_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAddInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
