# Generated by Django 2.2.13 on 2020-08-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_book_informed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='acrolama_profit',
            new_name='admin_profit',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='teachers_profit',
            new_name='partner_profit',
        ),
    ]
