# Generated by Django 2.2.19 on 2021-05-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_abocounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment_rosponse',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
    ]
