# Generated by Django 2.2.19 on 2021-05-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_book_comment_rosponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='comment_rosponse',
            new_name='comment_response',
        ),
    ]
