# Generated by Django 2.2.4 on 2019-10-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20190827_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Adress', 'verbose_name_plural': 'Adresses'},
        ),
    ]
