# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('addresse', models.CharField(max_length=250)),
                ('numero', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=250)),
                ('option', models.CharField(max_length=5)),
                ('allergies', models.CharField(max_length=300)),
                ('date', models.DateField()),
            ],
        ),
    ]
