# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fest',
            name='update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fest',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
