# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_auto_20180105_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fest',
            old_name='addresse',
            new_name='address',
        ),
    ]
