# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_auto_20180105_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='fest',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
