# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-06 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('teachers', models.TextField(blank=True, max_length=120, null=True)),
                ('workshop', models.TextField(blank=True, max_length=300, null=True)),
                ('prerequisites', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
