# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-06 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='date',
            field=models.DateField(default='2018-03-08'),
            preserve_default=False,
        ),
    ]
