# Generated by Django 2.2.6 on 2019-11-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiovisual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_height',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='image_width',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='images/', width_field='image_width'),
        ),
    ]
