# Generated by Django 2.2.2 on 2019-06-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiovisual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(upload_to='videos/'),
        ),
    ]
