# Generated by Django 2.2.16 on 2020-09-24 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audiovisual', '0005_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='mob',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/mob/'),
            preserve_default=False,
        ),
    ]
