# Generated by Django 2.2.16 on 2020-09-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiovisual', '0006_image_mob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='mob',
            field=models.ImageField(editable=False, upload_to='images/mob/'),
        ),
    ]
